name: Run Vitest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # (Node 18 veya 20 daha güncel, tavsiye ederim.)

    - name: Install dependencies
      run: |
        cd test
        npm install

    - name: Run Vitest tests
      run: |
        cd test
        npm run test
